[build]
    publish = "__sapper__/export/"
    command = "npm run export"

[[headers]]
    for = "/*"
    [headers.values]
        Content-Security-Policy = "default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self';base-uri 'self';form-action 'self'"
