[dev]
    framework = "svelte-kit"

[build]
    publish = "build/"
    command = "npm run build"

[[headers]]
    for = "/*"
    [headers.values]
#        Content-Security-Policy = "default-src 'self' *.portfolioris.nl;   img-src 'self';     style-src 'self' 'unsafe-inline';     script-src 'self' 'unsafe-inline' 'unsafe-eval' *.portfolioris.nl  unpkg.com;"
        X-Frame-Options = "SAMEORIGIN"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy = "no-referrer"
        Permissions-Policy = "geolocation=(self)"

[[redirects]]
    from = "https://me.portfolioris.nl/*"
    to = "https://www.portfolioris.nl/:splat"
    status = 301
    force = true

[[redirects]]
    from = "https://portfolioris-nl.netlify.app/*"
    to = "https://www.portfolioris.nl/:splat"
    status = 301
    force = true

[[redirects]]
    from = "/img/*"
    to = "/.netlify/builders/img"
#    to = "/.netlify/functions/img"
    status = 200

[[redirects]]
    from = "/image/*"
    to = "/image"
    status = 200

