[dev]
    framework = "svelte"

[build]
    publish = "dist/"
    command = "npm run build"

[functions]
    node_bundler = "esbuild"

[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "SAMEORIGIN"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy = "no-referrer"
        Permissions-Policy = "geolocation=(self)"

[[redirects]]
    from = "https://me.portfolioris.nl/*"
    to = "https://www.portfolioris.nl/:splat"
    status = 301
    force = true

[[redirects]]
    from = "https://portfolioris-nl.netlify.app/*"
    to = "https://www.portfolioris.nl/:splat"
    status = 301
    force = true

[[redirects]]
    from = "/img/*"
    to = "/.netlify/builders/img"
    status = 200
