[build]
    publish = "build/"
    command = "npm run export"
[[headers]]
    for = "/*"
    [headers.values]
        Content-Security-Policy = "default-src 'self' portfolioris.nl;   img-src 'self' res.cloudinary.com;     style-src 'self';     script-src 'self' 'unsafe-inline' portfolioris.nl;"
