[[headers]]
    for = "/*"
    [headers.values]
#        Content-Security-Policy = "default-src 'self' *.portfolioris.nl;   img-src 'self';     style-src 'self' 'unsafe-inline';     script-src 'self' 'unsafe-inline' 'unsafe-eval' *.portfolioris.nl  unpkg.com;"
#        Content-Security-Policy = "default-src 'self' *.portfolioris.nl;   img-src 'self';     style-src 'self' 'unsafe-inline';     script-src 'self'  *.portfolioris.nl  unpkg.com 'nonce-foobar';"
        X-Frame-Options = "SAMEORIGIN"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy = "no-referrer"
        Permissions-Policy = "geolocation=(self)"
