# .github/workflows/main.yml

name: Trigger Netlify Build
on:
  schedule:
    # Run at 0100 daily
    - cron: '0 1 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5fb3efba3344193eaa84f33b
